language: java
jdk: oraclejdk8

install:
- mkdir -p $HOME/.gradle
- echo "gradle.publish.key=$GRADLE_PUBLISH_KEY" >> $HOME/.gradle/gradle.properties
- echo "gradle.publish.secret=$GRADLE_PUBLISH_SECRET" >> $HOME/.gradle/gradle.properties

- echo "https://${GITHUB_TOKEN}:@github.com" > "$HOME/.git-credentials"
- git config --global user.name "$(git log -1 --format=format:%an)"
- git config --global user.email "$(git log -1 --format=format:%ae)"
- git config --global credential.helper store
- git config --global core.autocrlf input
- git config --global push.default current

script:
- ./gradlew check

- |
  mkdir build/publish
  cp -av acceptance-test/doc-generator/build/swagger-ui build/publish
  cp -av acceptance-test/html-generator/build/swagger-html build/publish

- |
  pushd build/publish
  git init
  git add .
  git commit -m 'Release example docs'
  git branch -m gh-pages
  git remote add origin "https://github.com/$TRAVIS_REPO_SLUG"
  git push origin -f
  popd

after_success:
- test ${TRAVIS_TAG} && ./gradlew publishPlugins
